function Version = GetVersionFromDirectoryName(RSim)

    DirectoryNames = cellfun(@(c)   strrep(strrep(c,'r3d',''),'ie','')  ,...
                                    RSim.ValidVersionDirectoryNames     ,...
                                    'UniformOutput', false);
    Version = cellfun(@(c)  Interpose(num2str(c),'.'),...
                            DirectoryNames,'UniformOutput',false);
    
end