function [] = ThrowWarning(RSim,WarningID,varargin)
    
    
    switch(WarningID)
        
        case('VerfiyInstallation:AbsentRootFolder')
            warning(...
                'RELAPSimulation:VerfiyInstallation:AbsentRootFolder'   ,...
                ['The default root folder for RELAP5 ''%s'' does '      ,...
                'not exist. Please specify an existing root '           ,...
                'folder to run simulations.'                            ],...
                RSim.Root);
            
        case('SetValidVersion:NoInstalledVersion')
             warning(...
                'RELAPSimulation:SetValidVersion:NoInstalledVersion',...
                ['No installation directory for a version of RELAP ',...
                'was not found in the root directory ''%s''. Not '  ,...
                'simulations can be run.'                           ],...
                RSim.Root);

        otherwise
    end
    
    
end