function CVcontainer = ContainerConStructor(WhichContainer,Number)
	
	Integer		= uint64(0)			;
	Real		= double(0)			;
	
	NCGTable	= struct('HeaderInfo',{{Char(4),Real}}	                    ,...
		                 'Data'      , {repmat({Char(16),Real},25,1)}		);
	
	CVprototype	= struct('ID'            , {{Char(16),Integer}}				,...
		                 'Type'          , Char(16)							,...
						 'ThermoSwitch'  , {{Char(8),Char(5),Char(14)}}		,...
						 'Velocities'    , [Real,Real]						,...
						 'FlowAreas'     , {{Char(4),Real}}					,...
						 'PoolAtmSwitch' , {{Char(8),Char(10),Char(11)}}    ,...
                         'PressTempData' , {{Char(4),Real}}                 ,...
						 'PoolAddition'  , Real                             ,...
						 'AtmAddition'   , {{Char(4),Real}}                 ,...
						 'NCGData'       , NCGTable                         ,...
						 'PoolAtmBound'  , {{Char(4),Real,Real,Real}}		,...
						 'VoidFraction'  , Real								,...
						 'Fog'           , {{Char(4),Real}}                 ,...
						 'VolAltTable'   , repmat(Real,25,2)                ,...
						 'Sources'       , repmat(Real,2,6)                 );
					 
	CVcontainer = CVprototype;
	
	function Filler = Char(Length)
		Filler = repmat('-',1,Length);
	end
	
	
end