function Container = ContainerConStructor(WhichContainer,Number)
	
% ---------------------------------------------------------------------
%	Variables that will allocate the maximum memory necessary for a 
%	model.  A string analogue called "Char" exists as the last
%	sub-function in this file.
%
	Integer		= uint64(0)			;
	Real		= double(0)			;

% ---------------------------------------------------------------------
%	Select Package to allocate for.
%
	switch(lower(WhichContainer))
		case({'cv','cvh','controlvolume','control volume'})
			Prototype	= AllocateControlVolumeContainer()						;
			
			
		case({'fl','fp','flow path','flowpath'})
			Prototype	= AllocateFlowPathContainer		()						;
			
			
		case({'hs','heatstructure','heat structure'})
			Prototype	= AllocateHeatStructureContainer()						;
			
		otherwise
			error('Package ''%s'' has no supported allocation.',WhichContainer)	;
	end

% ---------------------------------------------------------------------
%	Replicate the struct to the number of divisions requested
%
	Container = repmat(Prototype,Number,1);
	
	
%                                                                              %
%                             End Of Main Program                              %
% ============================================================================ %
% ============================================================================ %



% ============================================================================ %
%                              Sub-Function Block                              %
% ============================================================================ %

% ---------------------------------------------------------------------
%	Control Volume Package allocation
%
	function CVcontainer = AllocateControlVolumeContainer()
		NCGTable	= struct(													 ...
					  'HeaderInfo',{{Char(4),Real}}								,...
					  'Data'      , {repmat({Char(16),Real},25,1)}				);
			
		CVcontainer = struct(													 ...
					  'ID'           , {{Char(16),Integer}}						,...
					  'Type'         , {{Char(16)}}								,...
					  'ThermoSwitch' , {{Char(8),Char(5),Char(14)}}				,...
					  'Velocities'   , {{Real,Real}}							,...
					  'FlowAreas'    , {{Char(4),Real}}							,...
					  'PoolAtmSwitch', {{Char(8),Char(10),Char(11)}}			,...
					  'PressTempData', {{Char(4),Real}}							,...
					  'PoolAddition' , {{Real}}									,...
					  'AtmAddition'  , {{Char(4),Real}}							,...
					  'NCGData'      , NCGTable									,...
					  'PoolAtmBound' , {{Char(4),Real,Real,Real}}				,...
					  'VoidFraction' , {{Real}}									,...
					  'Fog'          , {{Char(4),Real}}							,...
					  'VolAltTable'  , {repmat({Real},25,2)}					,...
					  'Sources'      , {repmat({Real},2,6)}						);
	end
%
% ---------------------------------------------------------------------


% ---------------------------------------------------------------------
%	Flow Path Package allocation
%
	function FLcontainer = AllocateFlowPathContainer()
		FLcontainer = struct(													 ...
					  'ID'         , {{Char(16),Integer}}						,...
					  'Connections', {{Char(16),Char(16),Real,Real}}			,...
					  'Geometry'   , {repmat({Real},1,5)}						,...
					  'JxnSwithces', {{Real,Char(22),Char(22)}}					,...
					  'LossCoeffs' , {repmat(Real,1,4)}							,...
					  'Velocities' , {{Real,Real}}								,...
					  'MomExchLen' , {{Real}}									,...
					  'EDFInput'   , {{Char(16)}}								,...
					  'Blockage'   , {{Char(12),repmat(Integer,1,4),Real}}		,...
					  'Segments'   , {repmat({Real   , Real, Real , Real		,...
									   Char(6), Real, Char(16)}, 20,1)}			,...
					  'MomFluxMod' , {{Real,Real,Char(16),Char(16)}}			);
	end
%
% ---------------------------------------------------------------------	
	

% ---------------------------------------------------------------------
%	Heat Structure Package allocation
%
	function HScontainer = AllocateHeatStructureContainer()
		
		BoundInfo	= struct(													 ...
					  'Condition',{{Char(10),Char(16),Char(16),Char(3)}}		,...
					  'Radiation',{{Real,Char(10),Real}}						,...
					  'PoolInfo' ,{{Char(3),Real,Real}}							,...
					  'CritScale',{{Real,Real,Real,Real}}						,...
					  'Addition' ,{{Real,Real,Real}}							);
		
		
		HScontainer = struct(													 ...
					  'ID'         , {{Char(16),Integer}}						,...
					  'GeneralInfo', {{Char(16),Char(3)}}						,...
					  'ElevOrient' , {{Real,Real}}								,...
					  'Multiply'   , {{Real}}										,...
					  'Source'     , {{Char(2),Integer,Real}}					,...
					  'Nodes'      , {repmat({Integer,Real,Real					,...
					                   Real,Char(24),Real},20,1)}				,...
					  'LeftBound'  , BoundInfo									,...
					  'RightBound' , BoundInfo									,...
					  'FilmTrack'  , {{Char(3)}}								);
	end
%
% ---------------------------------------------------------------------	
	

% ---------------------------------------------------------------------
%	Function that will allocate the manual maximum of string length.
%
	function Filler = Char(Length)
		Filler = repmat('-',1,Length);
	end
%
% ---------------------------------------------------------------------	

%                                                                              %
%                          End Of Sub-Function Block                           %
% ============================================================================ %
% ============================================================================ %

end